### ISSUE TITLE
`search_people` function always return empty list

### ISSUE THREAD

**Issue by linda-benboudiaf** [tomquirk/linkedin-api#319]
NB : Cookies session is valid and the connexion to the API is working as well !

**Comment by weknin** [comment]
This seems to happen to me on all of the search functions, the response has a 403 Forbidden status code.

**Comment by FujiwaraChoki** [comment]
Have the same problem...

**Comment by gursheyss** [comment]
https://github.com/tomquirk/linkedin-api/pull/332#issue-1846896485

**Comment by bschilder** [comment]
This is occurring for me as well when using the `current_company`. It seems this wasn't fixed by #332 

```python
company_urn = ['1399', '62701122', '67383135', '33794684']
people = api.search_people(current_company=company_urn)
people
## []
```
I can see GSK ('1339') does indeed have employees listed:
https://www.linkedin.com/company/gsk/people/

Do you know what might be going on here @tomquirk ?

**Comment by tomquirk** [comment]
Hi @linda-benboudiaf @weknin @FujiwaraChoki @gursheyss @bschilder 

I have a potential fix in version 2.1.1. Please give it a try and let me know if it solves your issues.

```sh
pip install linkedin-api==2.1.1
```

**Comment by transitive-bullshit** [comment]
Some small things have changed on linkedin's side:

- change `queryId=voyagerSearchDashClusters.bb967969ef89137e6dec45d038310505` in the request (instead of `voyagerSearchDashClusters.b0928897b71bd00a5a7291755dcd64f0`)
- change `_type` to `$type` everywhere it's referenced in the response JSON
- `searchDashClustersByAll` is an object, not an array
- `entityResult` may not exist directly in the search results entity array, but rather `*entityResult` may point to an entry in the `included` array, so the `EntityResultViewModel` resolution logic needs a slight tweak
- (I've made these changes to a TS port; just posting here for visibility)

cc @tomquirk

**Comment by bw2** [comment]
Same issue here. 
search_people was working two days ago, but now always returns an empty list.
