### ISSUE TITLE
CI/CD and PyPI

### ISSUE THREAD

**Issue by szepnapot** [tomquirk/linkedin-api#36]
First of all, thanks for this great project! 👍 
already built a cool little linkedin bot with it 👨‍💻 

One thing made me a bit sad it that the [docs](https://github.com/tomquirk/linkedin-api/blob/master/DOCS.md) not in align with the latest PyPI package.
(`linkedin.get_invitations` and `linkedin.reply_invitation` are missing).

That's when I realized that most of the recent changes can only be used if you install the package from source, which ofc not a big problem just a little uncomfy.

Can we set up a CI/CD pipeline which auto deploy to PyPI?

**Comment by tomquirk** [comment]
@szepnapot great to hear you're putting this project to good use!

Totally agree, I think there are enough people using it now that automated PyPI deployments makes sense. I'll look into setting up Travis in the next couple of weeks.

**Comment by szepnapot** [comment]
@tomquirk ping if you need any help with it ;)

**Comment by tomquirk** [comment]
Alright, emailed Travis. I want to get it set up on travis-ci.com but this repo is in a weird state because I once activated it on travis-ci.org...hopefully get it fixed tomorrow 😂

**Comment by tomquirk** [comment]
decided not to do it at this time. Reason being is we can't run the tests in Travis (or anywhere) - they fail because Linkedin challenges us, I think because of IP and it's way too much effort to set up a proxy for testing.

We could do the auto-deploy, but I'd like just to just keep it manual for now. Don't worry - I will be sure to keep things up to date with PyPI now :)
