### ISSUE TITLE
Adding support for Linkedin Premium features

### ISSUE THREAD

**Issue by kingbar1990** [tomquirk/linkedin-api#57]
Does api work with premium accounts?

**Comment by tomquirk** [comment]
SHouldn't make a difference I wouldn't expect 😄

**Comment by devkarim** [comment]
@tomquirk I guess he meant the features that are concerning Premium LinkedIn subscription. Since I'm dealing with a similar project now, do you have any idea how to deal with sales navigator search? I don't seem to find anything useful in Network tab but I found that request URL in the page source. I believe that's it:

`{"request":"/sales-api/salesApiPeopleSearch?q\u003DpeopleSearchQuery\u0026start\u003D0\u0026count\u003D25\u0026query\u003D(doFetchHeroCard:true,keywords:test,recentSearchParam:(doLogHistory:true),searchHistoryParam:(doLogHistory:true),spotlightParam:(selectedType:ALL),trackingParam:(sessionId:WRoOTOKyS6+8ofaZWZZRPA\u003D\u003D),doFetchFilters:true,doFetchHits:true,doFetchSpotlights:true)\u0026decoration\u003D%28degree%2CentityUrn%2CfirstName%2ClastName%2CfullName%2CobjectUrn%2CgeoRegion%2Chighlight%28com.linkedin.sales.profile.profileHighlights.MentionedInTheNewsHighlight!_nt%3Dcom.linkedin.sales.deco.common.profile.highlights.DecoratedMentionedInTheNewsHighlight%28articleName%2Ccount%2Csource%2Curl%29%2Ccom.linkedin.sales.profile.profileHighlights.ProfileHighlights!_nt%3Dcom.linkedin.sales.deco.common.profile.highlights.DecoratedProfileHighlights%28sharedConnection%28sharedConnectionUrns*~fs_salesProfile%28entityUrn%2CfirstName%2ClastName%2CfullName%2CpictureInfo%2CprofilePictureDisplayImage%2CpresenceStatus%29%29%2CteamlinkInfo%28totalCount%29%2CsharedEducations*%28overlapInfo%2CentityUrn~fs_salesSchool%28entityUrn%2ClogoId%2Cname%2Curl%2CschoolPictureDisplayImage%29%29%2CsharedExperiences*%28overlapInfo%2CentityUrn~fs_salesCompany%28companyPictureDisplayImage%2CentityUrn%2Cname%2CpictureInfo%29%29%2CsharedGroups*%28entityUrn~fs_salesGroup%28entityUrn%2Cname%2ClargeLogoId%2CsmallLogoId%2CgroupPictureDisplayImage%29%29%29%2Ccom.linkedin.sales.profile.profileHighlights.RecentPositionChangeHighlight!_nt%3Dcom.linkedin.sales.deco.common.profile.highlights.DecoratedRecentPositionChangeHighlight%28companyUrn%2CcompanyName%2Cduration%2Ctitle%29%29%2CteamlinkIntrosHighlight%2CopenLink%2Cpremium%2Cteamlink%2CpendingInvitation%2CprofilePictureDisplayImage%2Cviewed%2Csaved%2CcrmStatus%2CtrackingId%2CrecommendedLeadTrackingId%2ClistCount%2CcurrentPositions*%2Ctags*%2CpastPositions*%2CmatchedArticles*%2CfacePiles*%2CsharedConnectionsHighlight%28count%29%29","status":200,"body":"bpr-guid-186952"}`

The syntax seems to be quite complicated though 😅

**Comment by tomquirk** [comment]
Nice @devkarim , Yep, that response looks pretty typical. You'll want to decode that though so it makes more sense, something like `JSON.parse(decodeURIComponent(x))` in browser console might do the trick.

**Comment by tomquirk** [comment]
But yes, I see what you guys are asking - can we add Linkedin Premium features (I guess its called Sales Navigator) to the api? I say yes, but we'll need some though around it. As I don't have or want Premium account, it would entail someone who does working out the implementation.

Intuitivaley, I think an API like `linkedin.premium.search()` (i.e. put everything under `premium` namespace)  might make some sense - what do you guys think?

**Comment by devkarim** [comment]
JSON.parse(decodeURIComponent(x)) looks pretty neat, thanks! I got a Premium account from someone so I can give it a shot once I get free since I'm anyway going to build a project via those features. I guess it's somehow similar to the traditional search so I might mix them up.

**Comment by Ulixestoitaca** [comment]
Did you make any progrress about Sales Navigator? Which is different from Premium for my knowledge

**Comment by devkarim** [comment]
@Ulixestoitaca yeah I guess, I did some progress but it seems to be quite complicated due to the syntax they use for searching.

**Comment by Ulixestoitaca** [comment]
May I ask if, after research has been executed, profile list is the same as standard research?

**Comment by tomquirk** [comment]
Unfortunately, I don't have access to a Premium account or one with sales navigator. I'd be more than happy to guide someone through implementing this though - let me know and we can set something up

**Comment by quesurifn** [comment]
I've been working on a JS library based on Tom's work. I've used it in an
MVP but I don't believe I've published it yet.

Anyway, salesnavigator is neat. You have to scrape the HTML but it offers a
way of turning emails to linkedin profile links which is super powerful.
Unfortunately it's rate-lmited per diem pretty lowley.

>

**Comment by devkarim** [comment]
> May I ask if, after research has been executed, profile list is the same as standard research?

Not that much as far as I remember, I had to create one on my own though

**Comment by Ulixestoitaca** [comment]
Hello,
you can get a free test account for a month. In case I could provide 1/2 accounts more in order to get more time

Il 21 nov 2019 10:59 PM, Tom Quirk <notifications@github.com> ha scritto:

Unfortunately, I don't have access to a Premium account or one with sales navigator. I'd be more than happy to guide someone through implementing this though - let me know and we can set something up

**Comment by digimonkskywalker** [comment]
I am looking for the same feature is there any updates? When I tried to send a request to sales-api by tweaking some of the linkedin_api it is giving me 400 responses.

According to my investigation, I think, linkedin produces key for every sales search. It's like a tracking Id.

**Comment by Rydgel** [comment]
Do you guys know if you can fetch the profile number of followers (if the profile is premium, they have a followers count)

**Comment by sneko** [comment]
Also interested to get the LinkedIn URLs of followers of a company page.

Anyone has tried this in the past?

Thank you,
