### ISSUE TITLE
API and DigitalOcean

### ISSUE THREAD

**Issue by kingbar1990** [tomquirk/linkedin-api#78]
I`ve set up server on DigitalOcean, but API through Challenge, but on local machine all works right. Have any ideas how to get around this case?

**Comment by tomquirk** [comment]
Yea, this will be because Linkedin has previously captured your IP or some additional details from your local machine that they're using to identify you. When they get a request from some random Droplet, they throw the challenge because it doesn't match with your local machine.

Your best bet is to use proxies and set up your account so that it's only ever accessed over the same IP (or maybe similar geographic regions)
