### ISSUE TITLE
Add ability to pass cookies into Linkedin constructor

### ISSUE THREAD

**Issue by JannikZed** [tomquirk/linkedin-api#91]
Hi there,
I'm really happy that I found this library. Very good work so far :) 
I would like to ask you for the best way to load cookies instead of using the login mechanism from you. We get the cookies of different account users in a different way and don't want to store any sensitive user data. 
Should be easy to implement - right? I can also try to create a pull request if you give me a little hint to the right direction :)

**Comment by crouinicrouina** [comment]
Hey,

I just found this library, it's great ! Awesome reverse engineering work done :+1: 

I believe I have a similar need as @JannikZed. I'm trying to run this library from Google cloud platform. For some reason, I'm getting the _CHALLENGE_ exception whenever I try to login using my credentials but if I login using the cached cookies, it works fine.

To answer the question, to use cookies to login, one could do something like that (quick and dirty solution) : 

```
def __init__(
        self,
        username,
        password,
        *,
        authenticate=True,
        refresh_cookies=False,
        debug=False,
        proxies={},
        cookies=None, # Add this argument
    ):
        self.client = Client(
            refresh_cookies=refresh_cookies, debug=debug, proxies=proxies
        )
        logging.basicConfig(level=logging.DEBUG if debug else logging.INFO)
        self.logger = logger
        
        # Modify this part like below
        if authenticate:
            if cookies:
                  self.client.authenticate(username, password)
           else:
                  self.client.self._set_session_cookies(cookies)
```

and you would call it like this 

```
api = Linkedin(None, None, cookies=cookies) # make sure that type(cookies) == <class 'requests.cookies.RequestsCookieJar'>
```

I didn't try this code but I quickly read the library's code and I guess it should work.

**Comment by crouinicrouina** [comment]
Actually I think I may have misunderstood your question. Are you instead looking for a custom method to load the cookies (e.g : using a custom `CookieRepository` class ?). 

As a matter of fact, I myself need to use a custom `CookieRepository` class because I run my app in a serverless container in which I can't write to disk. To save the cookies, I need custom logic. 

If I get to this step (need to sort the cookies refreshing / login challenge from my google server container), I will likely create a PR to implement this. Hint : once again, a quick and dirty method would be to add an extra argument to the `Linkedin` class constructor so that it accepts a custom `CookieRepository` class
